etc/pam_script: also apply security checks to the script directory

diff --git a/etc/pam_script b/etc/pam_script
--- a/etc/pam_script
+++ b/etc/pam_script
@@ -19,17 +19,11 @@ basedir=`dirname $0`
 fname=`basename $0`
 PAMSCRIPTDIR=${PAMSCRIPTDIR:-$basedir/pam-script.d}
 
-runscript () {
-	script="$1"
-	shift
-
-	if [ ! -e "$script" ]; then
-		return 0
-	fi
-
-	stat_output=`/usr/bin/stat -c "%A:%u:%g" "$script"`
+goodperms () {
+	local path="$1"
+	stat_output=`/usr/bin/stat -c "%A:%u:%g" "$path"`
 	if [ $? -ne 0 ]; then
-		echo "$0: Could not stat script $script" 1>&2
+		echo "$0: Could not stat path $path" 1>&2
 		return 1
 	fi
 
@@ -38,9 +32,20 @@ runscript () {
 	world_write_bit=${stat_output:8:1}
 
 	if [ ${world_write_bit} != "-" -o "$owner" -ne 0 -o "$group" -ne 0 ]; then
-		echo "$0: Unsafe permissions for script $script; Rejecting execution." 1>&2
+		echo "$0: Unsafe permissions for path $path; Rejecting execution." 1>&2
 		return 1
 	fi
+}
+
+runscript () {
+	script="$1"
+	shift
+
+	if [ ! -e "$script" ]; then
+		return 0
+	fi
+
+	goodperms "$script" || return 1
 
 	/bin/sh "$script" "$@"
 	return $?
@@ -58,6 +63,8 @@ if [ x"$fname" != x"pam_script" ]; then
 	*_ses_open)	mtype='_ses_open' ;;
 	*_ses_close)	mtype='_ses_close' ;;
 	esac
+
+	goodperms "$PAMSCRIPTDIR" || exit $PAM_SCRIPT_STATUS
 
 	for script in $PAMSCRIPTDIR/*$mtype; do
 		runscript "$script" $@ || PAM_SCRIPT_STATUS=1
